apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: v1.14.3
    helm:
      values: |
        provider: aws
        aws:
          region: ca-central-1
        domainFilters:
          - sulemannav.com
        policy: upsert-only
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::012525608560:role/external-dns-role
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true