apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: v26.0.0
    helm:
      values: |
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        providers:
          kubernetesIngress:
            enabled: true
            allowExternalNameServices: true
            namespaces:
              - default
              - traefik
              - argocd
              - monitoring
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true